### ISSUE TITLE
Is there a vscode version?

### ISSUE THREAD

**Issue by GeneralLi95** [humbinal/hexo-front-matter#1]
Thank you for this useful package. Do you have the plan to make a vscode version.

**Comment by humbinal** [comment]
> Thank you for this useful package. Do you have the plan to make a vscode version. 

Very good suggestions. I'll consider them in the near future.

**Comment by humbinal** [comment]
Hi, @GeneralLi95 , The hexo-front-matter for vscode version published.
plugin-name: hexo-fromt-matter
plugin-url: [https://marketplace.visualstudio.com/items?itemName=humbinal.hexo-fromt-matter](https://marketplace.visualstudio.com/items?itemName=humbinal.hexo-fromt-matter)
github-repo:  [https://github.com/humbinal/hexo-front-matter-vscode](https://github.com/humbinal/hexo-front-matter-vscode)
